export enum NomProduit {
  eset_protect_entry = 'eset_protect_entry',
  eset_protect_entry_on_prem = 'eset_protect_entry_on_prem',
  eset_protect_advanced = 'eset_protect_advanced',
  eset_protect_advanced_on_prem = 'eset_protect_advanced_on_prem',
  eset_protect_essential = 'eset_protect_essential',
  eset_protect_essential_on_prem = 'eset_protect_essential_on_prem',
  eset_protect_essential_plus_on_prem = 'eset_protect_essential_plus_on_prem',
  eset_protect_enterprise_on_prem = 'eset_protect_enterprise_on_prem',
  eset_home_security_essential = 'eset_home_security_essential',
  eset_protect_enterprise = 'eset_protect_enterprise',
  eset_endpoint_encryption = 'eset_endpoint_encryption',
  eset_endpoint_encryption_pro = 'eset_endpoint_encryption_pro',
  eset_mail_security = 'eset_mail_security',
  eset_smart_security_premium = 'eset_smart_security_premium',
  eset_secure_authentication = 'eset_secure_authentication',
  eset_internet_security = 'eset_internet_security',
  eset_server_security = 'eset_server_security',
  eset_protect_mail_plus = 'eset_protect_mail_plus',
  eset_protect_complete = 'eset_protect_complete'
}

/** Liste des produits pour les champs "produit" dans contrats et interventions */
export const PRODUIT_LIST: string[] = [
  'ESET',
  'Fortinet',
  'Palo Alto',
  'Veeam',
  'Proofpoint',
  'Wallix',
  'Rapid7',
  'CrowdStrike',
  'VMware',
  'Splunk',
  'One Identity',
  'SecPoint',
  'Bitdefender',
  'Netskope',
  'F5',
  'Fortra',
  'SentinelOne',
  'Malwarebytes',
  'Infoblox',
  'Varonis',
  'Microsoft',
  'Imperva',
  'Cisco'
];